### ISSUE TITLE
[<_UILabelLayer: 0x600000293380> display] Issue

### ISSUE THREAD

**Issue by MBKwon** [Patrick-Kladek/pkDebugFramework#1]
I got this message in console. My environment is 'macOS 10.12 / xcode 8'. it works well in my colleague's xcodes. but it isn't working in my mac. could you check this issue.

[<_UILabelLayer: 0x600000293380> display]: Ignoring bogus layer size (911.000000, 111331.000000), contentsScale 3.000000, backing store size (2733.000000, 333993.000000)

**Comment by Patrick-Kladek** [comment]
From the error message I assume that one of your properties store a huge amount of data. CocoaDebugView internal call -sizeToFit on a textfield which resulted in a huge frame.
I updated the project so the textfields which displays the data are limited in size. This size can be changed in the CocoaDebugSettings or by loading a plist-file which is demonstrated in the mac-demo.

If this did not fix your error please provide a more detailed information about your custom class which produces the error (properties types (NSString, NSData, ...) and the amount of data it holds)

You can also exclude properties by calling 'debugViewWithExcludingProperties
ofObject:' (more in the wiki). That my fix your error by exclude the property which stores the huge amount of data till we fix this bug.

**Comment by MBKwon** [comment]
TY for your fast reponse. This library is useful to inspect cocoa projects for debugging. you're great~!!
